[project]
name = "comfyui_jankhidiffusion"
description = "Janky implementation of HiDiffusion for ComfyUI. Enables generating at resolutions higher than what the model was trained for. Only supports SD 1.x (maybe 2.x) and SDXL."
version = "0.8.5"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/blepping/comfyui_jankhidiffusion"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "blepping"
DisplayName = "comfyui_jankhidiffusion"
Icon = ""

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [ 
    "comfyui_jankhidiffusion",
    "comfyui_jankhidiffusion.py",
]

[tool.setuptools.package-dir]
"comfyui_jankhidiffusion" = "."
"comfyui_jankhidiffusion.py" = "py"


[project.entry-points."comfyui.custom_nodes"]
comfyui_jankhidiffusion = "comfyui_jankhidiffusion"


[tool.setuptools.package-data]
"*" = ["**/*.js" ]